language: java
sudo: true
jdk:
    - openjdk8
addons:
    sonarcloud:
        organization: adam-g-klein
        token: 92ea6894152e1658a51bf7f26fe39e74c57cdcc5
before_install:
  - chmod +x mvnw
script:
- mvn spring-boot:run
- sonar-scanner
